name: flip_card_game
description: A simple flip card game for Windows.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0  # Diperbarui ke versi terbaru untuk mengatasi error C++ MSVC

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/video/

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 256