name: Build Flutter Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Generate Windows Platform Files
        run: flutter create . --platforms=windows

      - name: Get Dependencies
        run: flutter pub get

      - name: Generate App Icon
        run: dart run flutter_launcher_icons

      # Mencegah bentrok versi C++ bawaan plugin audioplayers dengan MSVC terbaru
      - name: Fix C++ Error
        run: Add-Content -Path windows/CMakeLists.txt -Value "add_compile_definitions(_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS)"

      - name: Build Windows Executable
        run: flutter build windows --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FlipCardGame-Windows
          path: build/windows/x64/runner/Release/